Document Vue
parcel-bundler/website pull request #634
Opened 2020-07-21 18:40 UTC by 101arrowz

Documents the functionality added by parcel-bundler/parcel#4892.

2020-07-21 19:17 UTC, DeMoorJasper requested changes
Could you create the files for the fix link comments, and just write in them TODO: Write this page or something like we did with javascript and pretty much all other languages.

Also I'm not sure if all of this should be a recipe, vue is actually also a language of itself in the parcel 1 docs we made a language/asset type page for it instead of a recipe. You can still add a recipe as a quick getting started with vue doc though

2020-07-21 19:22 UTC, 101arrowz commented
I was thinking of Vue as a parallel to React rather than a full-blown language. I'll move it to the languages section, but at that point you could call JSX a language of its own and move React to the languages category as well. Do you want me to document SFC syntax in `languages` and other stuff in `recipes`?

2020-07-21 22:15 UTC, mischnic commented on src/recipes/react.md
> +{% sample %}
```suggestion
{% sample "parcel index.html" %}
```
This was supposed to show that Parcel should be pointed to the HTML entry, as opposed to Webpack for example. I guess I changed to template for `sample` at some point and missed this.

2020-07-21 22:19 UTC, mischnic commented
At least for me, a "language" means "a specific filetype/extension" for Parcel. Recipes are examples that don't really contain new information by themselves but make it easier to get started.

With that definition, Vue should be a language.


- Is there some official documentation regarding blocks that we can link to?
- Is `.vuerc` an official config file or is it only for blocks (for the loader)? If it's the former then it should probably have it's own section as well (and a link to the Vue docs).

2020-07-21 22:20 UTC, mischnic commented on src/languages/vue.md
> +Note that Parcel 2 _does not support Vue 2_ if you plan to use SFCs; you must use [Vue 3 beta](https://github.com/vuejs/vue-next) or later.
```suggestion
Note that Parcel does not support using SFCs with Vue 2, you must use [Vue 3 beta](https://github.com/vuejs/vue-next) or later.
```

2020-07-21 22:21 UTC, mischnic commented on src/languages/vue.md
> +Parcel 2 uses the same HMR injection as the official [vue-loader](https://github.com/vuejs/vue-loader) for Webpack, so you'll have a fast, reactive development experience.
```suggestion
Parcel uses the same HMR injection as the official [vue-loader](https://github.com/vuejs/vue-loader) for Webpack, so you'll have a fast, reactive development experience.
```

2020-07-21 23:08 UTC, 101arrowz commented
Custom blocks are not part of the Vue core but are instead an opinionated feature added for vue-loader. The way I implemented custom blocks is _completely different_ (vue-loader load your script at build time as opposed to runtime), but most things that can be done with vue-loader can be done in my implementation. That's why I don't link to the actual docs for custom blocks.

2020-07-22 06:38 UTC, DeMoorJasper approved these changes

2020-07-22 06:39 UTC, merged

2020-07-22 07:17 UTC, mischnic commented
> Custom blocks are not part of the Vue 

- Would it make sense then to briefly describe what Custom Blocks are (for someone who only knows Vue core)?

- Are any of the other settings of https://cli.vuejs.org/config/#vue-config-js apply useful/used by the Parcel transformer?

2020-07-22 16:21 UTC, 101arrowz commented
The vast majority of Vue+Parcel users will have used `vue-loader` at some point (since that's what Vue CLI uses) and will know what custom blocks are. Moreover, the example I provided is pretty self-explanatory.

None of the options in `vue.config.js` really apply to Parcel - Vue CLI is meant to be a very simplified skin over webpack, so nearly all of the options (e.g. `pwa.workboxPluginMode`) are not relevant and should be specified elsewhere.

2020-07-22 16:35 UTC, mischnic commented
> will know what custom blocks are.

> The way I implemented custom blocks is completely different

I think they should be described in more detail

2020-07-23 03:26 UTC, 101arrowz commented
Implementation is different, concepts are the same. It's just code injected at runtime to modify the component instance. The example I provided is very self-explanatory.

2020-07-23 09:17 UTC, mischnic commented
Alright, let's leave it as is until someone opens an issue asking for more details