Dark search popover
parcel-bundler/website pull request #764
Opened 2020-11-14 21:14 UTC by mischnic

Closes https://github.com/parcel-bundler/website/issues/737

![Bildschirmfoto 2020-11-14 um 21 58 32](https://user-images.githubusercontent.com/4586894/99157126-be1ec600-26c6-11eb-866f-068f406d9b21.png)

2020-11-14 21:15 UTC, mischnic commented on .eleventy.js
> +    cleanCSSOptions: {
that css minified would also remove the first rule after
```
html.dark {
  .algolia-autocomplete {
    .ds-dropdown-menu {
```

2020-11-15 08:45 UTC, DeMoorJasper requested changes

2020-11-15 08:45 UTC, DeMoorJasper commented on src/doc-styles.scss
> +  .algolia-autocomplete {
Can't you add `/* clean-css ignore:start */` above this line and `/* clean-css ignore:end */` at the end of this css block to skip removal of these lines?

Not sure if we should completely opt-out from optimising for this little bit of css

2020-11-15 09:15 UTC, mischnic commented on src/doc-styles.scss
> +  .algolia-autocomplete {
> Not sure if we should completely opt-out from optimising for this little bit of css

I've reordered the rules so that cleancss seems to work correctly now.

The difference was surprisingly small:
disabled: 19kb
level 0: 16kb
level 1 (default): 15kb

2020-11-15 09:55 UTC, DeMoorJasper commented on src/doc-styles.scss
> +  .algolia-autocomplete {
oh awesome, probably means we don't have a lot of unnecessary css?

2020-11-15 09:55 UTC, DeMoorJasper approved these changes

2020-11-15 09:56 UTC, merged